name: dottunes

publish_to: 'none'
version: 1.5.0+2
# run update.sh after changing the version

environment:
  sdk: '>=3.4.1 <4.0.0'
  flutter: ^3.22.2

dependencies:
  get_it: ^8.0.2
  super_cupertino_navigation_bar: ^2.1.2
  enefty_icons: ^1.0.7
  glassmorphism_ui: ^0.3.0
  salomon_bottom_bar: ^3.3.2
  rive_animated_icon: ^2.0.3
  glass_kit: ^4.0.1
  animated_switcher_plus: ^1.1.0
  animated_notch_bottom_bar: ^1.0.3
  audio_service: ^0.18.14
  material_floating_search_bar_2: ^0.5.0
  flutter_sliding_box: ^1.1.5
  draggable_home: ^1.0.5
  audio_session: ^0.1.21
  hugeicons: ^0.0.7
  carousel_slider: ^5.0.0

  m3_carousel: ^2.0.2
  flashy_tab_bar2: ^0.0.10
  google_nav_bar: ^5.0.6
  lucide_icons_flutter: ^1.1.2
  cached_network_image: ^3.3.1
  dynamic_color: ^1.7.0
  file_picker: ^8.0.6
  fluentui_system_icons: ^1.1.246
  flutter:
    sdk: flutter
  flutter_flip_card: ^0.0.6
  flutter_localizations:
    sdk: flutter
  go_router: ^14.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  html: ^0.15.4
  http: ^1.2.0
  intl: ^0.19.0
  just_audio: ^0.9.39
  path_provider: ^2.1.3
  rxdart: ^0.27.7
  url_launcher: ^6.3.0
  youtube_explode_dart: ^2.2.1
  crystal_navigation_bar: ^1.0.2
  shared_preferences: ^2.3.5

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.1
  flutter_test:
    sdk: flutter
  translations_cleaner: ^0.0.5

  # flutter_lints: ^2.0.0

flutter:
  generate: true
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/licenses/
    - assets/music.gif
    - assets/images/
    - assets/googlemusic.gif
    - assets/bg.png
    - assets/nothing-font-5x7.ttf
    - assets/

  fonts:
    - family: paytoneOne
      fonts:
        - asset: fonts/paytone/PaytoneOne-Regular.ttf

    - family: Nothing
      fonts:
        - asset: fonts/Nothing.otf.ttf
    - family: Gatte
      fonts:
        - asset: assets/GatteModern.otf



flutter_native_splash:
  color: '#ffffff'
  image: assets/images/splash.png
  color_dark: '#151515'
  image_dark: assets/images/splash.png

  android_12:
    image: assets/images/splash.png
    icon_background_color: '#ffffff'
    image_dark: assets/images/splash.png
    icon_background_color_dark: '#151515'

flutter_launcher_icons:
  android: 'launcher_icon'
  adaptive_icon_background: '#191919'
  adaptive_icon_foreground: 'assets/images/ic_launcher_foreground.png'
  adaptive_icon_round: 'assets/images/ic_launcher_round.png'
  image_path: 'assets/images/ic_launcher.png'
flutter_intl:
  enabled: true
